name: ci

on: [push, pull_request]

jobs:
  linux-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test

  cmake:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cmake -B build
      - run: cmake --build build --config Release
      - run: ctest --test-dir build --build-config Release --output-on-failure
